### ISSUE TITLE
no way to set option allowFuture

### ISSUE THREAD

**Issue by mprokopov** [jgraichen/rails-timeago#7]
from documentation:

> To support timestamps in the future, use the allowFuture setting:
> jQuery.timeago.settings.allowFuture = true;

but here is no such option support in gem

**Comment by olliebennett** [comment]
Perhaps helpful for others, I had a problem when implementing the proposed configuration.

I found that `timeago` seemed to have already been initialised before the `allowFuture` option was set, resulting in future dates/times not being processed.

In order to resolve the problem, I (re-)called `timeago()` after defining the configuration:

```js
//= require jquery
//= require rails-timeago
$.timeago.settings.allowFuture = true;
$('time').timeago();
``` 

Apologies for reviving an old issue. Let me know if you'd like more info, or - if this is a genuine problem - let me know how I can help.
